name: Daily Commit Workflow
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Update Daily Log
        run: |
          date >> daily_log.txt
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add daily_log.txt
          MESSAGE_BASE="5"
          TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')
          git commit -m "$MESSAGE_BASE - $TIMESTAMP"
          git push
